#! /usr/bin/env python3
import yagmail
# from counter_backup.py import tdip
import datetime
todays_date = datetime.date.today()
timedelta = datetime.timedelta(days=6)
date1 = todays_date
date2 = date1 - timedelta
day1 = date1.strftime("%d %b %y")
day2 = date2.strftime("%d %b %y")

## Enter email sending from and login pass word
yag = yagmail.SMTP("email@email.com", "password")

## Enter email address sending to
yag.send(to=['email@email.com'], subject="Totals for " + str(day2) + " -- " + str(day1), contents= "Please see attached for weekly totals.", attachments="/home/pi/counter.xlsx")
